-- Create the table for storing meeting logs
create table public.meeting_logs (
  id bigint generated by default as identity primary key,
  content jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.meeting_logs enable row level security;

-- Create a policy that allows anyone to insert (anon key)
-- Note: In a production app with auth, you would restrict this to authenticated users.
-- For this simple tool with just an API key, we allow 'anon' role to insert.
create policy "Enable insert for all users" on public.meeting_logs
  for insert with check (true);

-- Optional: Allow reading own logs if you implement auth later
-- For now, purely for saving logs.
create policy "Enable read for all users" on public.meeting_logs
  for select using (true);
