/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GeminiTranslatorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_GEMINI_TRANSLATOR = "gemini-translator-view";
var GeminiTranslatorView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
  }
  getViewType() {
    return VIEW_TYPE_GEMINI_TRANSLATOR;
  }
  getDisplayText() {
    return "Gemini Translator";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.createEl("h4", { text: "Gemini Translator" });
    const info = container.createEl("p", { text: "Loading Translator..." });
    info.style.fontSize = "0.8rem";
    info.style.color = "#888";
    const iframe = container.createEl("iframe");
    iframe.setAttribute("src", "http://localhost:5173");
    iframe.style.width = "100%";
    iframe.style.height = "calc(100% - 50px)";
    iframe.style.border = "none";
    iframe.setAttribute("allow", "microphone");
    const btnContainer = container.createEl("div");
    btnContainer.style.marginBottom = "10px";
    const btn = btnContainer.createEl("button", { text: "Reload / Set URL" });
    btn.onclick = () => {
      const newUrl = prompt("Enter Translator URL (e.g. http://localhost:5173 or https://your-deployed-app.com)", iframe.src);
      if (newUrl)
        iframe.setAttribute("src", newUrl);
    };
  }
  async onClose() {
  }
};
var GeminiTranslatorPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerView(
      VIEW_TYPE_GEMINI_TRANSLATOR,
      (leaf) => new GeminiTranslatorView(leaf)
    );
    this.addRibbonIcon("languages", "Open Gemini Translator", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-gemini-translator",
      name: "Open Gemini Translator",
      callback: () => {
        this.activateView();
      }
    });
  }
  async onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_GEMINI_TRANSLATOR);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: VIEW_TYPE_GEMINI_TRANSLATOR, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
